Adding Uninstall script for issue 168
redhat-et/microshift pull request #179
Opened 2021-07-23 12:34 UTC by tosin2013

Adding clean up script for issue 168
https://github.com/redhat-et/microshift/issues/168

2021-07-23 12:57 UTC, rootfs commented
/approve

2021-07-23 12:57 UTC, rootfs commented
/assign @oglok

2021-07-27 22:18 UTC, guymguym reviewed
Looks good to me!

2021-07-27 22:45 UTC, rootfs commented
thank you @guymguym 
wdyt @oglok

2021-07-27 22:45 UTC, rootfs commented
/ok-to-test

2021-08-02 15:48 UTC, oglok requested changes
Thanks @tosin2013 for pushing this PR. We really appreciate your contributions.

2021-08-06 16:50 UTC, copejon commented on hack/cleanup.sh
> +}
I believe these functions could be consolidated into a single line, killing and removing all containers:

`$ until crictl rmp --force --all; do sleep 1; done`

2021-09-19 09:40 UTC, jbpratt reviewed
Should the microshift binary also be removed from the system? Cleaning up firewall rules, selinux config, stopping crio and uninstalling packages (if the desire is to have this script clean up everything from the install script) may be needed as well.

2021-10-19 19:54 UTC, cooktheryan commented
@guymguym I would say with RPM we would have a more formal removal process. This is in my opinion a nice supplement to help when running the install.sh or doing local development to set you back at a close to beginning state

2021-10-19 20:00 UTC, guymguym commented
> @guymguym I would say with RPM we would have a more formal removal process. This is in my opinion a nice supplement to help when running the install.sh or doing local development to set you back at a close to beginning state

👍  Sounds good @cooktheryan !

2021-11-01 17:19 UTC, cooktheryan commented
closed will merge items in at #405

2021-11-01 17:19 UTC, closed without merging