Add script for rebasing onto later OKD version
redhat-et/microshift pull request #234
Opened 2021-08-31 14:18 UTC by fzdarsky

This patch adds a scripts/rebase.sh script that takes as parameter the OKD release version string to rebase to and then updates
* vendored packages to the ones used by that OKD release,
* image digests in pkg/release/release_*.go for architectures supported by OKD,
* manifests in the assets directory
based on the release image metadata.

Signed-off-by: Frank A. Zdarsky <fzdarsky@redhat.com>

Closes #232

2021-09-02 12:03 UTC, mangelajo requested changes
Some nits, and may be some useful ones ':D

2021-09-02 12:03 UTC, mangelajo commented on scripts/rebase.sh
> +    images="$(get_release_images ${REPOROOT}/pkg/release/release_${arch}.go | xargs)"
that ${REPOROOT} may need also quotes, but... not sure what would work exactly here...
```suggestion
    images=$(get_release_images "${REPOROOT}/pkg/release/release_${arch}.go" | xargs)
```

may be this? hmm

2021-09-02 12:03 UTC, mangelajo commented on scripts/rebase.sh
> +    case $(basename ${asset}) in
```suggestion
    case $(basename "${asset}") in
```

2021-09-02 12:03 UTC, mangelajo commented on scripts/rebase.sh
> +    updated_asset=$(find ${search_path} -name "${search_name}" -not -path "${search_exclude}" | tail -n 1)
```suggestion
    updated_asset=$(find "${search_path}" -name "${search_name}" -not -path "${search_exclude}" | tail -n 1)
```

2021-09-02 19:54 UTC, fzdarsky commented on scripts/rebase.sh
> +    cat ${file} | awk "BEGIN {output=0} /^)/ {output=0} {if (output == 1 && !match(\$0,\"// indirect\")) print \$0} /^${section}/ {output=1}"
added, thx

2021-09-02 19:54 UTC, fzdarsky commented on scripts/rebase.sh
> +        if [[ ! -z "${update_line}" ]]; then
added, thx

2021-09-02 19:54 UTC, fzdarsky commented on scripts/rebase.sh
> +    done < ${base_file}
added, thx

2021-09-02 19:54 UTC, fzdarsky commented on scripts/rebase.sh
> +    cat ${file} | awk "BEGIN {output=0} /^}/ {output=0} {if (output == 1) print substr(\$1, 2, length(\$1)-3)} /^var Image/ {output=1}"
added, thx

2021-09-02 19:55 UTC, fzdarsky commented on scripts/rebase.sh
> +   >&2 echo "You need to run this script as root or in a `buildah unshare` environment:"
yeah, bad markdown habit ;P

2021-09-02 19:55 UTC, fzdarsky commented on scripts/rebase.sh
> +    if [[ ${EMBEDDED_COMPONENTS} == *"${COMPONENT}"* ]]; then
added, thx

2021-09-02 19:55 UTC, fzdarsky commented on scripts/rebase.sh
> +    case $(basename ${asset}) in
fixed

2021-09-02 19:56 UTC, fzdarsky commented on scripts/rebase.sh
> +    updated_asset=$(find ${search_path} -name "${search_name}" -not -path "${search_exclude}" | tail -n 1)
fixed

2021-09-02 19:56 UTC, fzdarsky commented on scripts/rebase.sh
> +cat << EOF > ${REPOROOT}/go.mod
fixed

2021-09-03 14:29 UTC, mangelajo approved these changes

2021-09-03 14:29 UTC, mangelajo commented on scripts/rebase.sh
> +    images="$(get_release_images ${REPOROOT}/pkg/release/release_${arch}.go | xargs)"
I'm not sure if this still needs to be fixed, ^ @fzdarsky , probably I'm missing something, approving but have an eye before merge.

2021-09-06 12:40 UTC, fzdarsky commented on scripts/rebase.sh
> +    images="$(get_release_images ${REPOROOT}/pkg/release/release_${arch}.go | xargs)"
Found a combo that should work and updated.

2021-09-06 13:01 UTC, fzdarsky commented on scripts/rebase.sh
> +cat ${mnt}/release-manifests/image-references \
[x] done

2021-09-07 18:55 UTC, rootfs commented
/lgtm

2021-09-07 18:55 UTC, merged